accounts/urls.py
from django.urls import path
from .views import profile , signup , profile_edit ,myreservation ,mylisting

app_name='accounts'

urlpatterns = [
    path('signup',signup,name='signup'),
    path('profile/',profile,name='profile'),
    path('reservation/',myreservation,name='reservation'),
    path('mylisting/',mylisting,name='mylisting'),
    path('profile_edit/',profile_edit,name='profile_edit')
]

car/urls.py
from django.urls import path
from .views import CarList,CarDetail
from .api_view import CarAPIList, CarAPIDetail

app_name='car'


urlpatterns = [
    path('',CarList.as_view(),name='car_list'),
    path('<slug:slug>',CarDetail.as_view(),name='car_detail'),

    path('api/list',CarAPIList.as_view(),name='car_api_list'),
    path('api/list/<int:pk>',CarAPIDetail.as_view(),name='car_api_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('car/', include('car.urls',namespace='car')),
    path('', include('settings.urls',namespace='home')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('about/', include('about.urls',namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', include('dj_rest_auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('dj_rest_auth.urls')),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user=models.ForeignKey(User, related_name='user_profile', on_delete=models.CASCADE)
    image=models.ImageField(upload_to='profile/', blank=True,null=True)
    phone_number = models.CharField(max_length=50,blank=True,null=True)
    address=models.CharField(max_length=50,blank=True,null=True)

    def __str__(self) :
        return str(self.user)
    
    @receiver(post_save,sender=User)
    def create_user_profile(sender,instance,created,**kwargs):
        if created:
            Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from . models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','phone_number','address']

accounts/views.py
from django.shortcuts import redirect, render
from .models import Profile
from .forms import UserForm , ProfileForm , UserCreateForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from car.models import CarBook , Car
# Create your views here.

def signup(request):
    if request.method == 'POST':
        signup_form = UserCreateForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            # return redirect(reverse('login'))
            username = signup_form.cleaned_data['username']
            password = signup_form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('accounts:profile'))

    else:
        signup_form = UserCreateForm()

    return render(request,'registration/signup.html',{'signup_form':signup_form})



def profile(request):
    profile = Profile.objects.get(user = request.user)
    return render(request,'profile/profile.html',{'profile':profile})



def profile_edit(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST , instance=request.user)
        profile_form = ProfileForm(request.POST , request.FILES , instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            my_form = profile_form.save(commit=False)
            my_form.user = request.user
            my_form.save()
            messages.success(request, 'Profile details updated.')
            return redirect(reverse('accounts:profile'))

    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance = profile)

    return render(request,'profile/profile_edit.html',{
        'user_form' : user_form ,
        'profile_form' : profile_form
    })


def myreservation(request):
    property_list=PropertyBook.objects.filter(user=request.user)
    return render(request,'profile/reservation.html',{'property_list':property_list})

def mylisting(request):
    property_list=Property.objects.filter(owner=request.user)
    return render(request,'profile/mylisting.html',{'property_list':property_list})

accounts/templates/profile/mylisting.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block body %}



<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
			data-scrollax-parent="true">
			<div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
				<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
						class="mr-2"><a href="index.html">Home</a></span> <span>Hotel</span></p>
				<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
			</div>
		</div>
	</div>
</div>
<section class="ftco-section ftco-degree-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-9">
				<div class="row">
					{% for property in property_list %}
					  <div class="col-md-4 ftco-animate">
						<div class="destination">
							<a href="{{property.get_absolute_url}}"
								class="img img-2 d-flex justify-content-center align-items-center"
								style="background-image: url({{property.image.url}});">
								<div class="icon d-flex justify-content-center align-items-center">
									<span class="icon-search2"></span>
								</div>
							</a>
							<div class="text p-3">
								<div class="d-flex">
									<div class="one">
										<h3><a href="{{property.property.get_absolute_url}}">{{property.name}}</a></h3>
										<p class="rate">
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star-o"></i>
											<span>8 Rating</span>
										</p>
									</div>
									<div class="two">
										<span class="price per-price">${{property.price}}<br><small>/night</small></span>
									</div>
								</div>
								<p>{{property.description|safe|truncatewords:5}}</p>
								<hr>
								<p class="bottom-area d-flex">
									<span><i class="icon-map-o"></i> {{property.place}}</span>
									<span class="ml-auto"><a href="{{property.get_absolute_url}}">View Room</a></span>
								</p>
							</div>
						</div>
					  </div>
                    {% endfor %}
				</div>
			</div> <!-- .col-md-8 -->
		</div>
	</div>  
</section> <!-- .section -->

{% endblock body %}

accounts/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
			data-scrollax-parent="true">
			<div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
				<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
						class="mr-2"><a href="index.html">Home</a></span> <span>Hotel</span></p>
				<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6 mx-auto mt-5 mb-5">
		{{profile.user.username}}

		{{profile.user.email}}


		{{profile.phone_number}}

		{{profile.address}}



		<h5><a href="{% url 'accounts:profile_edit' %}">Edit Profile</a></h5>
		<h5><a href="{% url 'accounts:reservation' %}">My Reservation</a></h5>
		<h5><a href="{% url 'accounts:mylisting' %}">My Listing</a></h5>
		<h5><a href="{% url 'password_change' %}">Change Password</a></h5>
	</div>
</div>



{% endblock %}

accounts/templates/profile/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
			data-scrollax-parent="true">
			<div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
				<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
						class="mr-2"><a href="index.html">Home</a></span> <span>Hotel</span></p>
				<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
			</div>
		</div>
	</div>
</div>
<div class="row">
    <div class="col-md-4 mx-auto mt-5 mb-5">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary py-3">Edit Profile</button>
            {% endbuttons %}
        
        </form>
    </div>
 </div>
 {% endblock %}

accounts/templates/profile/reservation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block body %}



<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
			data-scrollax-parent="true">
			<div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
				<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
						class="mr-2"><a href="index.html">Home</a></span> <span>Hotel</span></p>
				<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
			</div>
		</div>
	</div>
</div>
<section class="ftco-section ftco-degree-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-9">
				<div class="row">
					{% for property in property_list %}
					  <div class="col-md-4 ftco-animate">
						<div class="destination">
							<a href="{{property.get_absolute_url}}"
								class="img img-2 d-flex justify-content-center align-items-center"
								style="background-image: url({{property.property.image.url}});">
								<div class="icon d-flex justify-content-center align-items-center">
									<span class="icon-search2"></span>
								</div>
							</a>
							<div class="text p-3">
								<div class="d-flex">
									<div class="one">
										<h3><a href="{{property.property.get_absolute_url}}">{{property.property.name}}</a></h3>
										<p class="rate">
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star-o"></i>
											<span>8 Rating</span>
										</p>
									</div>
									<div class="two">
										<span class="price per-price">${{property.property.price}}<br><small>/night</small></span>
									</div>
								</div>
								<p>{{property.description|safe|truncatewords:5}}</p>
								<hr>
								<p class="bottom-area d-flex">
									<span><i class="icon-map-o"></i> {{property.property.place}}</span>
									<span class="ml-auto"><a href="{{property.get_absolute_url}}">Add Review</a></span>
								</p>
							</div>
						</div>
					  </div>
                    {% endfor %}
				</div>
			</div> <!-- .col-md-8 -->
		</div>
	</div>  
</section> <!-- .section -->

{% endblock body %}