blog/urls.py
from django.urls import path
from . import views
from .api_view import post_list_api, post_detail_api, post_search_api


app_name='blog'



urlpatterns = [
    path('',views.PostList.as_view(),name='post_list'),
    path('<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('category/<str:slug>',views.PostByCategory.as_view(),name='post_by_category'),
    path('tags/<slug:slug>',views.PostByTags.as_view(),name='post_by_tags'),


    #api
    path('api/list',post_list_api,name='post_list_api'),
    path('api/list/<int:id>',post_detail_api,name='post_detail_api'),
    path('api/list/filter/<str:query>',post_search_api,name='post_search_api'),


]

car/urls.py
from django.urls import path
from .views import CarList,CarDetail
from .api_view import CarAPIList, CarAPIDetail

app_name='car'


urlpatterns = [
    path('',CarList.as_view(),name='car_list'),
    path('<slug:slug>',CarDetail.as_view(),name='car_detail'),

    path('api/list',CarAPIList.as_view(),name='car_api_list'),
    path('api/list/<int:pk>',CarAPIDetail.as_view(),name='car_api_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('car/', include('car.urls',namespace='car')),
    path('', include('settings.urls',namespace='home')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('about/', include('about.urls',namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', include('dj_rest_auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('dj_rest_auth.urls')),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
# Create your models here.
class Post(models.Model):
    author=models.ForeignKey(User, related_name = 'post_author',verbose_name = _('author'), on_delete = models.CASCADE)
    title= models.CharField(max_length = 200, verbose_name =_('title') )
    tags = TaggableManager(_('tag'))
    images=models.ImageField(_('image'),upload_to = 'post/')
    created_at=models.DateTimeField(_('created at'),default = datetime.datetime.now)
    description=models.TextField(_('description'),max_length = 10000)
    category=models.ForeignKey('Category', related_name ='post_category', verbose_name = _('category'), on_delete = models.CASCADE)
    slug=models.SlugField(_('url') , null = True, blank = True)
    active = models.BooleanField(default=False)
    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug=slugify(self.title)

       super(Post, self).save(*args, **kwargs) # Call the real save() method

    def __str__(self):
       return self.title


    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})



class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Post,Category
from taggit.models import Tag
from django.db.models import Count
from django.db.models.query_utils import Q

# Create your views here.
class PostList(ListView):
    model= Post
    paginate_by=2

    def get_queryset(self):
        name=self.request.GET.get('q','')
        object_list=Post.objects.filter(
            Q(title__icontains=name)|
            Q(description__icontains=name)
        )
        return object_list


class PostDetail(DetailView):
    model= Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] =Category.objects.all().annotate(post_count=Count('post_category'))#تنفيذ query لكل object من category
        context["tags"]=Tag.objects.all()
        context["recent_posts"]=Post.objects.all()[:3]
        return context


class PostByCategory(ListView):
    model=Post


    def get_queryset(self):
        object_list=Post.objects.filter(
            Q(category__name__icontains=self.kwargs['slug'])
        )
        return object_list



class PostByTags(ListView):
    model=Post
    def get_queryset(self):
        object_list=Post.objects.filter(
            Q(tags__name__icontains=self.kwargs['slug'])
        )
        return object_list

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block body %}
    <div class="c" style="background-image: url({% static 'images/bg_21.png' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="/">{% translate "Home" %}</a></span> <span class="mr-2"></span> <span>{% translate "Blog" %}</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">{% translate "Tips" %} &amp; {% translate "Articles" %}</h1>
          </div>
        </div>
      </div>
    </div>
    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3">{{post}}</h2>
            <p>{{post.description|safe}}</p>
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                {% for tag in tags.all %}
                  <a href="#" class="tag-cloud-link">{{tag}}</a>
                {% endfor %}
              </div>
            </div>



            <div class="pt-5 mt-5">
              <h3 class="mb-5"><strong>{% translate "Comments" %}</strong></h3>
                <div id="disqus_thread"></div>
            </div>

          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box">
              <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                <div class="form-group">
                  <span class="icon fa fa-search"></span>
                  <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3><strong>{% translate "Categories" %}<strong></h3>
                {% for category in categories %}
                  <li><a href="{% url 'blog:post_by_category' category %}">{{category}}<span>{{category.post_count}}</span></a></li>
                {% endfor %}
                </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3><strong>{% translate "Recent Blog" %}</strong></h3>
               {% for post in recent_posts %}
                <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({{post.images.url}});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">{{post}}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span>{{post.created_at|date:'j F Y'}}</a></div>
                    <div><a href="#"><span class="icon-person"></span> {{post.author}}</a></div>
                  </div>
                </div>
                </div>
               {% endfor %}
            </div>

            <div class="sidebar-box ftco-animate">
              <h3><strong>{% translate "Tag Cloud" %}</strong></h3>
              <div class="tagcloud">
                {% for tag in tags  %}
                  <a href="{% url 'blog:post_by_tags' tag %}" class="tag-cloud-link">{{tag}}</a>
                 {% endfor %}
                </div>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->


    <script>
      /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
      var disqus_config = function () {
      this.page.url = "https://127.0.0.1:8000/{{post.get_absolute_url}}";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "{{post.slug}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
      };
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://sakkni.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block body %}

 <div class="c" style="background-image: url({% static 'images/bg_3.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="/">{% translate "Home" %}</a></span> <span>{% translate "Blog" %}</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">{% translate "Tips" %}Tips &amp;
                    {% translate "Articles" %}  </h1>
            </div>
        </div>
    </div>
 </div>


 <section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            {% for post in object_list %}
             <div class="col-md-3 d-flex ftco-animate">
                <div class="blog-entry align-self-stretch">
                    <a href="{{post.get_absolute_url}}" class="block-20" style="background-image: url({{post.images.url}});">
                    </a>
                    <div class="text p-4 d-block">
                        <span class="tag">{% translate "Tips" %},{% translate "Travel" %} </span>
                        <h3 class="heading mt-3"><a href="{{post.get_absolute_url}}">{{post}}</a>
                        </h3>
                        <div class="meta mb-3">
                            <div><a href="#"><{{post.created_at|date:'F j Y'}}></a></div>
                            <div><a href="#">{{post.author}}</a></div>
                            <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                        </div>
                    </div>
                </div>
             </div>

            {% endfor %}
        </div>
        {% if is_paginated %}


        <div class="row mt-5">
           <div class="col text-center">
               <div class="block-27">
                   <ul>

                       {% if page_obj.has_previous %}
                             <li><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
                       {% else %}
                         <li class="disabled"><span>&lt;</span></a></li>
                       {% endif %}
                       {% for i in paginator.page_range %}

                        {% if page_obj.number == i %}
                         <li class="active"><span>{{i}}</span></li>
                        {% else %}
                          <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endif %}
                       {% endfor %}
                       {% if page_obj.has_next %}
                             <li><a href="?page={{page_obj.next_page_number}}">&lt;</a></li>
                       {% else %}
                         <li class="disabled"><span>&lt;</span></a></li>
                       {% endif %}
                   </ul>
               </div>
           </div>
         </div>

       {% endif %}
    </div>
 </section>


{% endblock body %}