about/urls.py
from django.urls import path
from .views import AboutView

app_name= 'about'

urlpatterns = [

    path('',AboutView.as_view(),name='about'),
]

blog/urls.py
from django.urls import path
from . import views
from .api_view import post_list_api, post_detail_api, post_search_api


app_name='blog'



urlpatterns = [
    path('',views.PostList.as_view(),name='post_list'),
    path('<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('category/<str:slug>',views.PostByCategory.as_view(),name='post_by_category'),
    path('tags/<slug:slug>',views.PostByTags.as_view(),name='post_by_tags'),


    #api
    path('api/list',post_list_api,name='post_list_api'),
    path('api/list/<int:id>',post_detail_api,name='post_detail_api'),
    path('api/list/filter/<str:query>',post_search_api,name='post_search_api'),


]

car/urls.py
from django.urls import path
from .views import CarList,CarDetail
from .api_view import CarAPIList, CarAPIDetail

app_name='car'


urlpatterns = [
    path('',CarList.as_view(),name='car_list'),
    path('<slug:slug>',CarDetail.as_view(),name='car_detail'),

    path('api/list',CarAPIList.as_view(),name='car_api_list'),
    path('api/list/<int:pk>',CarAPIDetail.as_view(),name='car_api_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('car/', include('car.urls',namespace='car')),
    path('', include('settings.urls',namespace='home')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('about/', include('about.urls',namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', include('dj_rest_auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('dj_rest_auth.urls')),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from .views import home,home_search ,category_filter , contact , dashboard ,news_letter_subscribe,reviews_view
from . import api_view

app_name='settings'


urlpatterns = [
    path('',home,name='home'),
    path('search',home_search,name='home_search'),
    path('newsletter',news_letter_subscribe,name='newsletter'),
    path('category/<slug:category>',category_filter,name='category_filter'),
    path('contact',contact,name='contact'),
    path('dashboard/',dashboard,name='dashboard'),
    path('about/api',api_view.about_api,name='about_api'),
    path('about/api/faq',api_view.faq_api,name='faq_api'),
    path('contact/api',api_view.contact_api,name='contact_api'),
    path('reviews/',reviews_view, name='reviews_view'),  # هنا يتم استدعاء الدالة الجديدة
]

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-11360001724"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'AW-11360001724');
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>SpeedSwitchCarRental</title>
  <link rel="icon" href="{% static 'images/icon.jpg' %}" type="image/x-icon">
</head>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="/">{{myfooter.name}}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="/" class="nav-link" style=color:terqiase>{% translate "Home" %}</a></li>
          <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link"
              style=color:red>{% translate "About" %}</a></li>
          <li class="nav-item"><a href="{% url 'settings:contact' %}" class="nav-link">{% translate "Contact Us" %}</a></li>
          <li class="nav-item"><a href="{% url 'settings:dashboard' %}" class="nav-link"
              style=color:red>{% translate "Dashboard" %}</a></li>
          <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link">{% translate "Blog"  %}</a></li>
          <form action="{% url 'set_language' %}" method="post" class="language-form">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="languageDropdown"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                {% if language.code == LANGUAGE_CODE %}
                {{ language.name_local }} ({{ language.code }})
                {% endif %}
                {% endfor %}
              </button>
              <div class="dropdown-menu" aria-labelledby="languageDropdown">
                {% for language in languages %}
                <button class="dropdown-item" type="submit" name="language" value="{{ language.code }}">
                  {{ language.name_local }} ({{ language.code }})
                </button>
                {% endfor %}
              </div>
            </div>
          </form>

        </ul>
      </div>
    </div>
  </nav>
  <!-- END nav -->

  {% block body %}

  {% endblock body %}

  <div class="fixed-booking-buttons">
    <a href="tel:+971523660709" class="btn btn-primary">
      <i class="fas fa-phone"></i> {% translate "Call Now" %}
    </a>
    <a href="https://wa.me/971523660709?text=Hello,%20I%20would%20like%20to%20know%20more%20about%20the%20car%20services%20you%20provide?%0A%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%20%D8%A7%D8%B1%D9%8A%D8%AF%20%D9%85%D8%B9%D8%B1%D9%81%D8%A9%20%D8%A7%D9%84%D9%85%D8%B2%D9%8A%D8%AF%20%D8%B9%D9%86%20%D8%AE%D8%AF%D9%85%D8%A7%D8%AA%20%D8%A7%D9%84%D8%B3%D9%8A%D8%A7%D8%B1%D8%A7%D8%AA%20%D8%A7%D9%84%D8%AA%D9%8A%20%D8%AA%D9%82%D8%AF%D9%85%D9%88%D9%86%D9%87%D8%A7%20%D8%9F"
      class="btn btn-success">
      <i class="fab fa-whatsapp"></i>{% translate "WhatsApp" %}
    </a>
  </div>




  <footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">{{myfooter.site_name}}</h2>
            <p>{{myfooter.description}}.</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="{{myfooter.twitter_url}}"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="{{myfooter.fb_url}}"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="{{myfooter.Instgram_url}}"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">{% trans "Information" %}</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'about:about' %}" class="py-2 d-block">{% trans "About" %}</a></li>
              <li><a href="{% url 'settings:contact' %}" class="py-2 d-block">{% trans "Service" %}</a></li>
              <li><a href="{% url 'settings:contact' %}" class="py-2 d-block">{% trans "Terms and Conditions" %}</a>
              </li>
              <li><a href="https://wa.me/+971523660709" class="py-2 d-block">{% trans "Become a partner" %}</a></li>
              <li><a href="https://wa.me/+971523660709" class="py-2 d-block">{% trans "Best Price Guarantee" %}</a></li>
              <li><a href="{% url 'settings:contact' %}" class="py-2 d-block">{% trans "Privacy and Policy" %}</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">{% trans "Customer Support" %}</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'about:about' %}" class="py-2 d-block">{% trans "FAQ" %}</a></li>
              <li><a href="https://wa.me/+971523660709" class="py-2 d-block">{% trans "Payment Option" %}</a></li>
              <li><a href="https://wa.me/+971523660709" class="py-2 d-block">{% trans "Booking Tips" %}</a></li>
              <li><a href="{% url 'about:about' %}" class="py-2 d-block">{% trans "How it works" %}</a></li>
              <li><a href="{% url 'settings:contact' %}" class="py-2 d-block"></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">{% trans "Have a Questions?" %}</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">{{myfooter.address}}</span></li>
                <li><a href="https://wa.me/+963960060827"><span class="icon icon-phone"></span><span
                      class="text">{{myfooter.phone_number}}</span></a></li>
                <li><a href="mailto:bilalqwider@yahoo.com"><span class="icon icon-envelope"></span><span
                      class="text">{{myfooter.mail}}</span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">

          <p>
            {% trans "Copyright" %} &copy; <script>document.write(new Date().getFullYear());</script> {% trans "All rights reserved" %} | {% trans "This website is made by" %} <i class="icon-heart" aria-hidden="true"></i><a href="https://www.linkedin.com/in/mohammad-bilal-qwider-077497245/" target="_blank">{% trans "Bilal Qwider" %}</a><i class="icon-heart" aria-hidden="true"></i>
          </p>
        </div>
      </div>
    </div>
  </footer>


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" /></svg></div>

  <!-- jQuery and jQuery plugins -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>

  <!-- Popper.js for Bootstrap dropdowns and tooltips -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>

  <!-- Bootstrap JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <!-- Other JavaScript libraries and your custom scripts -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBiCl6S-4IG7wpZHUtTZpf1ZAkd4iIvseI&sensor=false">
  </script>
  <script src="/js/google-places.js "></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/scrole.js' %}"></script>





</body>

</html>